name: Create Release

on:
    push:
        tags:
        - 'v*'
        
env:
  tag: ${{ github.ref }}
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
        
      - name: Creating temp.md
        run: |
            cd scripts/
            npm install axios --save
            node changelog.js ${{ secrets.release }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          body_path: |
            temp.md
          draft: false
          prerelease: false
